# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'record.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(252, 301)
        MainMenu.setMinimumSize(QtCore.QSize(252, 301))
        MainMenu.setMaximumSize(QtCore.QSize(252, 301))
        MainMenu.setStyleSheet("")
        self.clickBtn = QtWidgets.QPushButton(MainMenu)
        self.clickBtn.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.clickBtn.setCheckable(False)
        self.clickBtn.setDefault(False)
        self.clickBtn.setFlat(False)
        self.clickBtn.setObjectName("clickBtn")
        self.clickBtn.clicked.connect(lambda: self.onClickCmd("click"))
        self.moveToBtn = QtWidgets.QPushButton(MainMenu)
        self.moveToBtn.setGeometry(QtCore.QRect(90, 40, 75, 23))
        self.moveToBtn.setCheckable(False)
        self.moveToBtn.setObjectName("moveToBtn")
        self.typeBtn = QtWidgets.QPushButton(MainMenu)
        self.typeBtn.setGeometry(QtCore.QRect(170, 40, 75, 23))
        self.typeBtn.setObjectName("typeBtn")
        self.scrollBtn = QtWidgets.QPushButton(MainMenu)
        self.scrollBtn.setGeometry(QtCore.QRect(10, 70, 75, 23))
        self.scrollBtn.setObjectName("scrollBtn")
        self.waitBtn = QtWidgets.QPushButton(MainMenu)
        self.waitBtn.setGeometry(QtCore.QRect(90, 70, 75, 23))
        self.waitBtn.setObjectName("waitBtn")
        self.manualBtn = QtWidgets.QPushButton(MainMenu)
        self.manualBtn.setGeometry(QtCore.QRect(170, 70, 75, 23))
        self.manualBtn.setObjectName("manualBtn")
        self.copyBtn = QtWidgets.QPushButton(MainMenu)
        self.copyBtn.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.copyBtn.setObjectName("copyBtn")
        self.pasteBtn = QtWidgets.QPushButton(MainMenu)
        self.pasteBtn.setGeometry(QtCore.QRect(90, 100, 75, 23))
        self.pasteBtn.setObjectName("pasteBtn")
        self.endBtn = QtWidgets.QPushButton(MainMenu)
        self.endBtn.setGeometry(QtCore.QRect(170, 100, 75, 23))
        self.endBtn.setObjectName("endBtn")
        self.docText = QtWidgets.QPlainTextEdit(MainMenu)
        self.docText.setGeometry(QtCore.QRect(10, 150, 231, 31))
        self.docText.setObjectName("docText")
        self.infoLabel = QtWidgets.QLabel(MainMenu)
        self.infoLabel.setGeometry(QtCore.QRect(10, 240, 231, 31))
        self.infoLabel.setTextFormat(QtCore.Qt.PlainText)
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")
        self.docLabel = QtWidgets.QLabel(MainMenu)
        self.docLabel.setGeometry(QtCore.QRect(10, 130, 81, 16))
        self.docLabel.setObjectName("docLabel")
        self.valueLabel = QtWidgets.QLabel(MainMenu)
        self.valueLabel.setGeometry(QtCore.QRect(10, 190, 121, 16))
        self.valueLabel.setObjectName("valueLabel")
        self.valueText = QtWidgets.QPlainTextEdit(MainMenu)
        self.valueText.setGeometry(QtCore.QRect(10, 210, 231, 31))
        self.valueText.setObjectName("valueText")
        self.okBtn = QtWidgets.QPushButton(MainMenu)
        self.okBtn.setGeometry(QtCore.QRect(40, 270, 75, 23))
        self.okBtn.setObjectName("okBtn")
        self.pushButton_2 = QtWidgets.QPushButton(MainMenu)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 270, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.spinBox = QtWidgets.QSpinBox(MainMenu)
        self.spinBox.setGeometry(QtCore.QRect(200, 10, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(MainMenu)
        self.label.setGeometry(QtCore.QRect(170, 10, 47, 13))
        self.label.setObjectName("label")

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Pyautogui GUI"))
        self.clickBtn.setToolTip(_translate("MainMenu", "Mouse click"))
        self.clickBtn.setText(_translate("MainMenu", "Click"))
        self.moveToBtn.setToolTip(_translate("MainMenu", "Mouse move to"))
        self.moveToBtn.setText(_translate("MainMenu", "Move to"))
        self.typeBtn.setText(_translate("MainMenu", "Type"))
        self.scrollBtn.setText(_translate("MainMenu", "Scroll"))
        self.waitBtn.setText(_translate("MainMenu", "Wait"))
        self.manualBtn.setToolTip(_translate("MainMenu", "User input needed"))
        self.manualBtn.setText(_translate("MainMenu", "Manual"))
        self.copyBtn.setToolTip(_translate("MainMenu", "Copy selected text"))
        self.copyBtn.setText(_translate("MainMenu", "Copy"))
        self.pasteBtn.setToolTip(_translate("MainMenu", "Paste text"))
        self.pasteBtn.setText(_translate("MainMenu", "Paste"))
        self.endBtn.setToolTip(_translate("MainMenu", "End this program"))
        self.endBtn.setText(_translate("MainMenu", "End"))
        self.infoLabel.setText(_translate("MainMenu", "Move your mouse to the position.\nBefore pressing enter."))
        self.docLabel.setText(_translate("MainMenu", "Documentation"))
        self.valueLabel.setText(_translate("MainMenu", "Value - Type, Scroll, Wait"))
        self.okBtn.setText(_translate("MainMenu", "OK"))
        self.okBtn.setShortcut(_translate("MainMenu", "Return"))
        self.pushButton_2.setText(_translate("MainMenu", "CANCEL"))
        self.label.setText(_translate("MainMenu", "Line"))
